
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Thu Nov 21 14:16:00 CST 2013
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int rw_PRINT = 16;
  static final int PLUS = 10;
  static final int NOTEQ = 13;
  static final int RBRACE = 9;
  static final int RPAREN = 6;
  static final int SEMI = 4;
  static final int rw_BOOL = 15;
  static final int IDENTIFIER = 2;
  static final int LPAREN = 5;
  static final int LBRACE = 8;
  static final int INTLIT = 3;
  static final int EOF = 0;
  static final int ASG = 7;
  static final int MINUS = 11;
  static final int rw_INT = 17;
  static final int error = 1;
  static final int EQ = 12;
  static final int rw_IF = 14;
}

